name: Nix
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: NixOS/nix-installer-action@main

      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3.numtide.com

      - name: Build
        run: nix build --log-format bar-with-logs

      - name: Run lint
        run: nix develop -c just lint

      - name: Flake check
        run: nix flake check --log-format bar-with-logs
